//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt_19._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Right { get; set; }
        public string Mail { get; set; }
        public string Fio { get; set; }
        public string Name { get; set; }
    }
}
